# Generated by Django 5.2.5 on 2025-08-20 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='صورة المشروع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخبر')),
                ('description', models.TextField(verbose_name='وصف الخبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الذي أضاف الخبر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news_media/', verbose_name='ملف (صورة أو فيديو)')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='website.news')),
            ],
            options={
                'verbose_name': 'ملف وسائط',
                'verbose_name_plural': 'ملفات الوسائط',
            },
        ),
    ]
