# Generated by Django 5.2.5 on 2025-08-20 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='وصف الخبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='وصف الخبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان الخبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان الخبر'),
        ),
    ]
