# Generated by Django 5.2.5 on 2025-08-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_category_news_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="اسم التصنيف"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="اسم التصنيف"
            ),
        ),
    ]
