# Generated by Django 5.2.5 on 2025-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_category_name_ar_category_name_en"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "تصنيف"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AddField(
            model_name="project",
            name="name_ar",
            field=models.CharField(
                max_length=200, null=True, verbose_name="اسم المشروع"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="اسم المشروع"
            ),
        ),
    ]
