# Generated by Django 5.2.5 on 2025-08-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_category_options_remove_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "التصنيفات"},
        ),
    ]
