# Generated by Django 5.2.5 on 2025-08-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "التصنيفات", "verbose_name_plural": "التصنيفات"},
        ),
    ]
